# Numpy 모듈 
* 파이썬 라이브러리 중 하나 -> 주로 과학 연산에 사용 
* 배열(행렬 - 선행대수) 기능 
* 대용량 데이터 다룰때 - 선행대수, 푸리에 변환 ... 같은 수학함수에 최적화됨 


In [1]:
import numpy as np 

In [3]:
# array - 결국 행렬 뜻함 
# 1차원: 행만/ 2차원: 행,열/ 3차원: 행,열,면  

a = np.array([1,2,3,4])  #1차원 배열 생성 
print(a)

[1 2 3 4]


In [4]:
l = [1,2,3,4]
print(l)         #리스트와 다름 

[1, 2, 3, 4]


In [8]:
print(a.shape)
print(a.ndim)     #차원 
print(a.dtype)    #data type 
print(a.itemsize) #바이트 단위 크기 

(4,)
1
int64
8


In [10]:
#2차원 배열 생성
b = np.array([[1,2], [3,4]])   #꺽새가 차원이라 수가 생각하면 편함 
print(b)

[[1 2]
 [3 4]]


In [13]:
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

2
int64
8
32


In [15]:
#3차원 배열 생성 
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])  #2차원 데이터 나눔 

print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int64
8
64


In [16]:
# 하나의 숫자값 : 스칼라

s = np.array(1)        #하나의 데이터값이고, 1차원(벡터)와는 다른 것 
print(s)

1


In [17]:
#1차원 :벡터
v = np.array([1,2,3])
print(v)

[1 2 3]


In [18]:
#2차원 :행렬(Matrix)

m = np.array([[1,2,3], [1,2,3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [20]:
#3차원 :텐서(Tensor)

t = np.array([[[1,2], [1,2,]], [[1,2], [1,2]]])
print(t)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [ ]:
## 용어는 정리해두기 

In [22]:
#for문 이용해서 배열생성

f = np.array([i for i in range(0,10,2)])
print(f)

[0 2 4 6 8]


In [23]:
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


## numpy에서의 데이터 타입
* 숫자형 - 가장 많이 사용됨 
* 문자형
* 논리형 

### 숫자형
* 부호가 있는 정수 (signed integer) :음수가 있 - int
* 부호가 없는 정수 (Unsigned integer) : 음수가 없 -uint
* 실수 (floating point) - float
* 복소수 (complex) - complex

In [24]:
#int (8bit/ 16bit/ 32bit/ 64bit)   #데이터 저장범위가 다른것 

data = [1.1,2,3]
i = np.array(data, dtype = np.int32)   #int형으로 강제로 주었기에 실수 > 정수로 바뀜 
print(i)

[1 2 3]


In [66]:
data2 = [-1,2,3]

ui = np.array(data2, dtype = np.uint32)  #uint 32(0-4,294,967,295 범위임)  #-1 (초과값)이기에 맨 뒤에꺼가 출력된것  
print(ui)                                #따라서 이상하게 들어가면 데이터범위, 데이터타입 확인해볼 필요 있음! 

[4294967295          2          3]


In [25]:
#실수형
f = np.array(data, dtype = np.float64)
print(f)     #역시 정수형 > .0 실수형으로 

[1.1 2.  3. ]


In [27]:
#복소수
c = np.array([1+2j, 3+4j, 5+6j], dtype = np.complex64)

In [28]:
print(c.real)  #실수
print(c.imag)  #허수 - j 앞 

[1. 3. 5.]
[2. 4. 6.]


### 문자형 
* string_
* unicode_

In [29]:
#string_
data = [1,2,3]

s = np.string_(data)
print(s)              #byte 표기법으로 보여준것 

b'\x01\x02\x03'


In [30]:
print(s.dtype)        #S3 : string 3단어

|S3


In [33]:
data3 = [1,2,3,4,5]

s2 = np.string_(data3)      #s2 = np.array(data3, dtype = 'S')랑 같음 - 보는게 편해야할때

print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [35]:
#unicode_

u = np.array(data3, dtype='U')

print(u)                        #string이랑 다른 점 - 식별가능하게 나옴 
print(u.dtype)                  #한자리 뜻함 (1,2,3 이런거..)

['1' '2' '3' '4' '5']
<U1


### 논리형 (boolean)
* True(1), False(0)
* 비트 연산 사용 : &, | or, ^ xor, ~ not

In [36]:
l1 = np.array([True, False, True])  #논리형 배열 생성
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [38]:
#and 연산

and_ = np.logical_and(l1,l2)   #둘다 T여야하니까 False
print(and_)

[False False False]


### 데이터 형변환 (Cast, Casting 형변환)
* 데이터끼리 형태를 맞춰야 일단 계산할 수 있기에 
* 예시. 이미지 데이터 불러옴 > uint형으로 불러옴 > float로 분석 
(uint는 부호가 없는 정수형/ 이미지는 rgb로 0-455 니까 음수 필요없으니까)

In [40]:
data = [1.1,2,3]

a = np.float64(data)   #방법1 - np.데이터타입 
print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [41]:
a = a.astype(np.int64)  #2 - .astype(데이터타입)

print(a)
print(a.dtype)

[1 2 3]
int64


In [44]:
b = np.uint16(0)    #부호가 없으니까 0이 제일 작은값 

print(b)
print(b.dtype)

0
uint16


In [46]:
b=b-1              #빼주니까(값 있는거 연산하니까) int형으로 자동으로 바꿔서 빼준것   
print(b)
print(b.dtype)

-1
int64


In [47]:
c = np.uint16(-1)   #uint16: 0~65,535 범위 
print(c)

65535


## numpy의 산술연산

In [15]:
import time

data = [[1,2,3], [4,5,6]]
data2 = [[1,1,1], [2,2,2], [3,3,3]]

start_time = time.time()  #걸리는 시간 측정해서 저장함 

for i in range(len(data)):      #0,1까지 돌고
  for j in range(len(data[0])): #0,1,2번째 값까지 돌도록 
    #print('i: ',i, 'j: ',j )    #값이 아니라 인덱스 값만
    sum += data[i][j]

print(sum)

i:  0 j:  0
i:  0 j:  1
i:  0 j:  2
i:  1 j:  0
i:  1 j:  1
i:  1 j:  2
[68 70 72]


In [51]:
data = [[1,2,3], [4,5,6]]
data2 = [[1,1,1], [2,2,2], [3,3,3]]

len(data[0])

3

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#덧셈
sum = a+b
min = a-b
mul = a*b
div = a/b

print(sum, min, mul, div)                     #numpy에서 행렬 계산으로 for문보다 더 쉽게 계산 가능 

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


In [7]:
#지수 계산 - exp     
      
aa = np.exp(a)
print(aa)

[ 2.71828183  7.3890561  20.08553692]


In [8]:
#자연로그 :밑이 e - log

bb = np.log(b)   
print(bb)

[1.38629436 1.60943791 1.79175947]


In [9]:
#밑이 2인 로그 - log2

cc = np.log2(b)  
print(cc)

[2.         2.32192809 2.5849625 ]


In [12]:
#삼각함수 
d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)
cos_ = np.cos(d)
tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
## 있다는 것만 알면 됨/ 나중에 필요할때 찾아볼 수 있도록

## 배열의 연결과 분할

In [17]:
x = [1,2,3]
y = [4,5,6]

#더하려면 차원수 같아야!
concat = np.concatenate([x,y])   #연결 
print(concat)

[1 2 3 4 5 6]


In [20]:
##병합1 - concatenate

x2 = [[1,2], [3,4]]     #2x2 
y2 = [[4,5], [6,7]]

concat2 = np.concatenate([x2,y2], axis = 1)  #열로 병합(=열이 늘어남)
#concat2 = np.concatenate([x2,y2], axis = 0)  #행으로 병합(=행이 늘어남)
print(concat2)

[[1 2 4 5]
 [3 4 6 7]]


In [23]:
arr = np.arange(10)
print(arr)

arr.reshape(2,5)          #2행 5열로 모양 바꿔줌 > 이렇게 맞춰서 병합해야할수도!  ##

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
##병합2 - hstack/ vstack

#hstack : horizontal 수평 
#vstack : vertical 수직

h = np.hstack([x2,y2])
print(h)                  #옆으로/ 수평 - 열로 붙음 

[[1 2 4 5]
 [3 4 6 7]]


In [25]:
v = np.vstack([x2,y2])
print(v)                  #밑으로/ 수직 - 행으로 붙음 

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [30]:
##분할1 - hsplit/ vsplit 

x2 = np.array([[1,2], [3,4], [5,6]])  #dim없다고 나와서 array로 만들어줌 

h2 = np.hsplit(x2,2)   #수평방향의 행을 자르는 것 #따라서 열로 잘림 
print(h2)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [31]:
v2 = np.vsplit(x2,3)
print(v2)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


## 다양한 배열

In [32]:
#0행렬 -.zeros

zero = np.zeros([3,4])     #[3,4,2]하면 3차원 행렬 
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
#1행렬 - .ones

one = np.ones([3,4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
#대각행렬: 대각선1/ 나머지 0  - .eye

eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## numpy 제공함수

### 범용함수

In [36]:
#절댓값 - .abs

arr1 = np.array([-1,-2,-3,-4])
abs_arr = np.abs(arr1)

print(abs_arr)

[1 2 3 4]


In [37]:
#제곱근 - .sqrt

arr2 = np.array([1,4,9,16])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 2. 3. 4.]


### 집계함수

In [39]:
#평균 - .mean (실수형)

a = np.array([1,2,3,4,5])
a_mean = np.mean(a)
print(a_mean)

3.0


In [40]:
#중앙값 - .median (실수형)

b = np.array([1,3,5,7,9])
b_median = np.median(b)
print(b_median)

5.0


In [46]:
#최솟값 - .argmin (최솟값의 인덱스 반환!)

min = np.argmin(d)
print(min)

0


In [47]:
#최댓값 - .argmax (인덱스)
max = np.argmax(d)
print(max)

4


In [41]:
#표준편차 - .std (실수형)

c = np.array([1,2,3,4,5])
c_std = np.std(c)
print(c_std)

1.4142135623730951


In [42]:
#분산 - .var (실수형)

d = np.array([1,2,3,4,5])
d_var = np.var(d)
print(d_var)

2.0


In [43]:
#합계 - sum  (값으로 반환)
d_sum = np.sum(d)
print(d_sum)

15


In [44]:
#누적합계 - cumsum (배열형태로 반환!)

d_cumsum = np.cumsum(d)
print(d_cumsum)

[ 1  3  6 10 15]


In [48]:
#배열 안 True 하나라도 있는지 - .any

a = np.array([0,0,0,1])

a_true = np.any(a)
print(a_true)

True


In [50]:
#모든게 1이어야만 True - .all

a_all = np.all(a)
print(a_all)

False


In [51]:
#NaN (not a number) - .nan / nansum:nan을 0으로 대체하여 sum

a= np.array([1,2, np.nan, 4])
a_nsum = np.nansum(a)
sum_ = np.sum(a)            #그냥 sum은 nan 출력됨 

print(a_nsum)
print(sum_)     

7.0
nan


In [57]:
#조건에 맞는'값' 반환 - .where
d = np.array([1,2,3,4,5])

condition1 = np.where(d<3)                                                       #튜플!     
condition2 = np.where(d<3, d, 0)  #조건에 맞는 애들 빼고 나머지는 0으로 만들기   #배열! (!= 리스트) 
print(condition1)
print(condition2)

(array([0, 1]),)
[1 2 0 0 0]


## Boolean Indexing
* 조건에 따른 요소들을 판별해서 '새로운' 배열 만듦 
* 즉 원본데이터는 불변!

In [60]:
a = np.array([1,2,3,4,5,6,7,8,9,10])  #원본 데이터

#데이터분석할때 원본데이터는 건들이지 않는다!! 
#따라서 복사본을 항상 만들어서 분석하기!!! 

In [63]:
even_a = a[a % 2 == 0]  #boolean indexing #짝수만 
print(even_a)
print(a)                #원본 데이터는 변하지 않음! 

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


## Broadcast 브로드캐스트
* 크기가 다른 배열간의 연산 가능하게 해줌 
* 예시) 1차원, 2차원 

* 두 배열의 차원수가 다를경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을때까지 1을 추가한다. 
* 두 배열의 차원수가 같을 경우에도 크기가 1인 차원이 있다면, 다른 배열의 크기와 일치하도록 복제된다. 
* 두 배열의 차원수가 같은 경우에도 모든 차원의 크기가 같거나 1이라면, 모양이 같은 두 배열의 요소간 연산을 한다. 

In [64]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a+b
print(c)    #차원이 동일하기에 그냥 사칙연산 이용하면 됨 

[5 7 9]


In [65]:
d = np.array([[1], [2], [3]])   #차원 다른데        ##행렬은 2차원부터
e = np.array([4,5,6])                                #1차원은 벡터! 

f = d+e
print(f)                        #출력됨 -> numpy의 브로드캐스트 기능! 

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#벡터 1x3으로 바꾸면 
[[1,1,1]] 

In [ ]:
#즉, i) 먼저 같은 차원으로 - e가 벡터이므로 [[]]로 1x3 2차원으로 만듦
#    ii) 같은 차원이더라도, 다른 배열의 크기와 일치하도록 복제 - 양쪽에서 크기 1 차원있으므로 3까지 복제됨 
[[1 1 1      +   [[4 5 6      =  [[5 6 7  
  2 2 2            4 5 6           6 7 8
  3 3 3 ]]         4 5 6 ]]        7 8 9 ]]

##__

## 난수생성 함수
* random

In [1]:
import numpy as np 

In [3]:
#0~1사이 균일분포 뽑아줌 #2x2

a = np.random.rand(2,2)   
print(a)

[[0.49610827 0.59622982]
 [0.44524996 0.32248089]]


In [85]:
#표준 정규분포(평균이 0, 분산이 1) 안에서 랜덤값

b = np.random.rand(2,2)    
print(b)

[[0.2805454  0.12706513]
 [0.497162   0.11636277]]


In [10]:
#많이 사용 
#random한 정수값  #(최솟값, 최댓값, size)

c = np.random.randint(0,10,size = 5)     
print(c)

[1 8 8 0 9]


In [ ]:
c2 = np.random.randint(0,10,size = (2,2))   #size이거는 행렬 만들어줌   
print(c2) 

### shuffle 셔플
* 무작위로 값 섞는것 
* 원본 자체가 변함/ 복사본 생성이 안됨!! 

In [12]:
d = np.arange(10)       #0-9까지 값 생성 
np.random.shuffle(d)    #변수 할당할 필요없음(원래 원본이 변하니까) 
print(d)

[9 2 6 3 5 1 8 0 7 4]


### choice

In [18]:
#choice = np.random.choice(d, 5)           #중복 뽑 허용! 
#choice = np.random.choice(d, 5, replace = False)  #중복 비허용  
choice = np.random.choice(d, 5, p=[0.1,0.3,0.1,0.1,0,0,0.2,0,0.1,0.1]) #지정확률별로 뽑  #전체 확률은 1되어야
print(choice)

[9 8 4 2 6]


### permutation 순열 (nPr)

In [20]:
#permutation 순열 (nPr)
a = np.arange(10)
a_p = np.random.permutation(a)  #원본 안바뀜 

print(a)
print(a_p)

[0 1 2 3 4 5 6 7 8 9]
[1 5 3 4 0 8 6 2 9 7]


### 정규분포 따르는 난수

In [22]:
#정규분포 따르는 난수생성 
#a = np.random.normal('평균', '표준편차', '개수')   <-> random.rand 는 표준정규분포에서 난수생성 

a = np.random.normal(0,1,3)
print(a)

[-0.15864428  1.39142454  0.19993678]


# Pandas
* 데이터 자체를 분석, 파악
* 데이터 다루는데 초점
* 표(데이터 시각화)
* 정렬, 필터링, 그룹화, 집계시 


* 시계열 데이터 처리




In [ ]:
## 일반적인 Pandas 순서

데이터 로딩 및 저장
> 데이터 인덱싱 
> 결측치 처리 
> 데이터 변환 
> 데이터 집계 및 그룹화 

## 1번. Series
* 인덱스 자동 mapping됨 
* 인덱스 따로 지정할 수도 있음 

### 인덱싱

In [23]:
import pandas as pd 

In [25]:
s = pd.Series([1,2,3,4])   #값 - 리스트로 넣음 
print(s)                   #첫번째는 인덱스/ 두번째는 값이 자동으로 mapping됨!! -pandas 특징 

0    1
1    2
2    3
3    4
dtype: int64


In [26]:
s2 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})   # - 딕셔너리로 넣음 
print(s2)                                      #지정해준 인덱스!

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
s3 = pd.Series(5, index = [0,1,2])    #5 - 스칼라 값  
print(s3)                             #인덱스에 따라 자동으로 들어감 

In [27]:
#활용 
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
                                        #값을 따로 저장하고 series 만드는 방법 
series = pd.Series(data, index=index)   #값이 변해도 이 식은 안바껴도 됨 > 유지보수 쉬움 
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
s = pd.Series(data)  #인덱스값이 있으면 -> 데이터 찾는 시간 엄청나게 단축됨 
print(s)

### 슬라이싱
* 값을 긁어서 가져올뿐 / 원본은 그대로!

In [29]:
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [36]:
#series[0:4]   #0-3 idx까지  

#series[:4]    #0은 생략가능 
#series[:-1]   둘다 가능 #마지막 앞까지 끊기는 것  

0    1
1    2
2    3
3    4
dtype: int64

### Boolean indexing

In [39]:
print(series[series > 2])   #조건 만족하는 series값만 배열로 반환 
                            #a[a조건]!!

2    3
3    4
4    5
dtype: int64


In [41]:
#5보다 작은 시리즈 만들기
print(series[series < 5])

[0     True
 1     True
 2     True
 3     True
 4    False
 dtype: bool]

### Series 산술연산

In [42]:
series + 100   #한꺼번에 다 더해짐  #이건 그냥 계산한 결과일뿐 원본은 그대로임 

0    101
1    102
2    103
3    104
4    105
dtype: int64

In [ ]:
print(series + 100)
print(series - 100)
print(series * 100)
print(series ** 100)
print(series / 100)   #몫 float 
print(series % 100)
print(series // 100)  #몫 int 

###__

### Series 객체에 접근
* keys -> index 가리킴 / values 

In [86]:
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
print(series.keys)    #인덱스 자체를 뜻하지 않고/ 인덱스 객체를 뜻함(인덱스를 가리킴)

In [50]:
print(series.keys())
print(series.index)     #rangeindex는 Series만들때 pandas에서 자동생성 
print(series.values)
print(series.items())   #zip : 순회 가능, 쌍으로 이루어져 있음을 알 수 있 (index, value)

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [51]:
for index, value in s2.items():
  print(f'인덱스: {index}, 데이터: {value}')

인덱스: a, 데이터: 1
인덱스: b, 데이터: 2
인덱스: c, 데이터: 3
인덱스: d, 데이터: 4


In [88]:
s = pd.Series([10,20,30,40], index = ['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [89]:
#앞이론들과 여기를 구분!! 

#슬라이싱 말고 레이블로 접근하는 이유? 데이터가 숫자가 아니라 문자일때 (레이블 즉 특정 인덱스로 접근하고 싶을때)
### loc[레이블] -> 값만 반환    <-> at과의 차이 : 여러범위 가능 

print(s.loc['b'])   #loc : 행에 접근 메서드  #어떤 행인지 아니까 값만 
print(s.loc['b':'d'])   #슬라이싱 - 어딘지 모르니까 다 출력해줌 

20
b    20
c    30
d    40
dtype: int64


In [55]:
### iloc[열 index 숫자] -> 값 반환 

print(s.iloc[1])     #iloc :(행에 기반한) 열에 접근

20


In [57]:
print(s.iloc[1:3])   #iloc 끝 미포함/ 숫자는 일반 슬라이싱 <-> loc 레이블은 끝 포함 
#print(s.iloc[-1])

b    20
c    30
dtype: int64
40


In [90]:
#at :특정 인덱스 지정할때 - 그 값이 들어감 

print(s.at['b'])     

20


In [59]:
print(s.iat[0])      #i이므로 [숫자 index]로 검색 

10


In [61]:
#(error안나고) 없는 값에 대한 처리방법

print(s.get('e'))   
#print(s.get('e', default = -1)) 

None


### 결측값 (NaN, None)
* NaN(Not a Number) -> float
* None -> none 


* isna()
* isnull()

In [66]:
data = [1,2,3, NaN]
s = pd.Series(data)

print(s.isna())
print(s.isnull())

0    False
1    False
2    False
3     True
dtype: bool
0    False
1    False
2    False
3     True
dtype: bool


In [67]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [68]:
#비어있는 값 개수 확인 
print(s.isnull().sum())   

1


In [69]:
print(s.notnull().sum())

3


In [71]:
## 결측치 제거 -1. dropna()

s.dropna()   #해도 원본 그대로니까 s= 할당함 

In [73]:
##             -2. 결측치 0 으로 치환 - fillna()
s.fillna(0)
s

0    1.0
1    2.0
2    3.0
dtype: float64

### Series 함수

In [ ]:
s = pd.Series([1,3,5,7,9])

In [75]:
s.count()   #데이터 개수 

5

In [ ]:
s.min() #최솟값 
s.max() #최대값 

In [ ]:
print(s.mean())
print(s.median())
print(s.std())
print(s.var())

In [78]:
#기초통계 내용 출력 

s.describe()  

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64