# Numpy 모듈 
* 파이썬 라이브러리 중 하나 -> 주로 과학 연산에 사용 
* 배열(행렬 - 선행대수) 기능 
* 선행대수, 푸리에 변환 ... 같은 수학함수에 최적화됨 

In [1]:
import numpy as np 

In [3]:
# array - 결국 행렬 뜻함 
# 1차원: 행만/ 2차원: 행,열/ 3차원: 행,열,면  

a = np.array([1,2,3,4])  #1차원 배열 생성 
print(a)

[1 2 3 4]


In [4]:
l = [1,2,3,4]
print(l)         #리스트와 다름 

[1, 2, 3, 4]


In [8]:
print(a.shape)
print(a.ndim)     #차원 
print(a.dtype)    #data type 
print(a.itemsize) #바이트 단위 크기 

(4,)
1
int64
8


In [10]:
#2차원 배열 생성
b = np.array([[1,2], [3,4]])   #꺽새가 차원이라 수가 생각하면 편함 
print(b)

[[1 2]
 [3 4]]


In [13]:
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

2
int64
8
32


In [15]:
#3차원 배열 생성 
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])  #2차원 데이터 나눔 

print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
int64
8
64


In [16]:
# 하나의 숫자값 : 스칼라

s = np.array(1)        #하나의 데이터값이고, 1차원(벡터)와는 다른 것 
print(s)

1


In [17]:
#1차원 :벡터
v = np.array([1,2,3])
print(v)

[1 2 3]


In [18]:
#2차원 :행렬(Matrix)

m = np.array([[1,2,3], [1,2,3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [20]:
#3차원 :텐서(Tensor)

t = np.array([[[1,2], [1,2,]], [[1,2], [1,2]]])
print(t)

[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [ ]:
## 용어는 정리해두기 

In [22]:
#for문 이용해서 배열생성

f = np.array([i for i in range(0,10,2)])
print(f)

[0 2 4 6 8]


In [23]:
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


# numpy에서의 데이터 타입
* 숫자형 - 가장 많이 사용됨 
* 문자형
* 논리형 

## 숫자형
* 부호가 있는 정수 (signed integer) :음수가 있
* 부호가 없는 정수 (Unsigned integer) : 음수가 없 -유인트 
* 실수 (floating point)
* 복소수 (complex)

In [24]:
#int (8bit/ 16bit/ 32bit/ 64bit)   #데이터 저장범위가 다른것 

data = [1.1,2,3]
i = np.array(data, dtype = np.int32)   #int형으로 강제로 주었기에 실수 > 정수로 바뀜 
print(i)

[1 2 3]


In [66]:
data2 = [-1,2,3]

ui = np.array(data2, dtype = np.uint32)  #uint 32(0-4,294,967,295 범위임)  #-1 (초과값)이기에 맨 뒤에꺼가 출력된것  
print(ui)                                #따라서 이상하게 들어가면 데이터범위, 데이터타입 확인해볼 필요 있음! 

[4294967295          2          3]


In [25]:
#실수형
f = np.array(data, dtype = np.float64)
print(f)     #역시 정수형 > .0 실수형으로 

[1.1 2.  3. ]


In [27]:
#복소수
c = np.array([1+2j, 3+4j, 5+6j], dtype = np.complex64)

In [28]:
print(c.real)  #실수
print(c.imag)  #허수 - j 앞 

[1. 3. 5.]
[2. 4. 6.]


## 문자형 
* string_
* unicod_

In [29]:
#string_
data = [1,2,3]

s = np.string_(data)
print(s)              #byte 표기법으로 보여준것 

b'\x01\x02\x03'


In [30]:
print(s.dtype)        #S3 : string 3단어

|S3


In [33]:
data3 = [1,2,3,4,5]

s2 = np.string_(data3)      #s2 = np.array(data3, dtype = 'S')랑 같음 - 보는게 편해야할때

print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [35]:
#unicod_

u = np.array(data3, dtype='U')

print(u)                        #string이랑 다른 점 - 식별가능하게 나옴 
print(u.dtype)                  #한자리 뜻함 (1,2,3 이런거..)

['1' '2' '3' '4' '5']
<U1


## 논리형 (boolean)
* True(1), False(0)
* 비트 연산 사용 : &, | or, ^ xor, ~ not

In [36]:
l1 = np.array([True, False, True])  #논리형 배열 생성
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [38]:
#and 연산

and_ = np.logical_and(l1,l2)   #둘다 T여야하니까 False
print(and_)

[False False False]


## 데이터 형변환 (Cast, Casting 형변환)
* 데이터끼리 형태를 맞춰야 일단 계산할 수 있기에 
* 예시. 이미지 데이터 불러옴 > uint형으로 불러옴 > float로 분석 
(uint는 부호가 없는 정수형/ 이미지는 rgb로 0-455 니까 음수 필요없으니까)

In [40]:
data = [1.1,2,3]

a = np.float64(data)   #방법1 - np.데이터타입 
print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [41]:
a = a.astype(np.int64)  #2 - .astype(데이터타입)

print(a)
print(a.dtype)

[1 2 3]
int64


In [44]:
b = np.uint16(0)    #부호가 없으니까 0이 제일 작은값 

print(b)
print(b.dtype)

0
uint16


In [46]:
b=b-1              #빼주니까 int형으로 자동으로 바꿔서 빼준것   
print(b)
print(b.dtype)

-1
int64


In [47]:
c = np.uint16(-1)   #uint16: 0~65,535 범위 
print(c)

65535


# numpy의 산술연산

In [15]:
import time

data = [[1,2,3], [4,5,6]]
data2 = [[1,1,1], [2,2,2], [3,3,3]]

start_time = time.time()  #걸리는 시간 측정해서 저장함 

for i in range(len(data)):      #0,1까지 돌고
  for j in range(len(data[0])): #0,1,2번째 값까지 돌도록 
    #print('i: ',i, 'j: ',j )    #값이 아니라 인덱스 값만
    sum += data[i][j]

print(sum)

i:  0 j:  0
i:  0 j:  1
i:  0 j:  2
i:  1 j:  0
i:  1 j:  1
i:  1 j:  2
[68 70 72]


In [51]:
data = [[1,2,3], [4,5,6]]
data2 = [[1,1,1], [2,2,2], [3,3,3]]

len(data[0])

3

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

#덧셈
sum = a+b
min = a-b
mul = a*b
div = a/b

print(sum, min, mul, div)                     #numpy에서 행렬 계산으로 for문보다 더 쉽게 계산 가능 

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


In [7]:
#지수 계산 - exp     
      
aa = np.exp(a)
print(aa)

[ 2.71828183  7.3890561  20.08553692]


In [8]:
#자연로그 :밑이 e - log

bb = np.log(b)   
print(bb)

[1.38629436 1.60943791 1.79175947]


In [9]:
#밑이 2인 로그 - log2

cc = np.log2(b)  
print(cc)

[2.         2.32192809 2.5849625 ]


In [12]:
d = np.array([0, np.pi/2, np.pi])

sin_ = np.sin(d)
cos_ = np.cos(d)
tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
## 있다는 것만 알면 됨/ 나중에 필요할때 찾아볼 수 있도록

# 배열의 연결과 분할

In [17]:
x = [1,2,3]
y = [4,5,6]

#더하려면 차원수 같아야!
concat = np.concatenate([x,y])   #연결 
print(concat)

[1 2 3 4 5 6]


In [20]:
##병합1 - concatenate

x2 = [[1,2], [3,4]]     #2x2 
y2 = [[4,5], [6,7]]

concat2 = np.concatenate([x2,y2], axis = 1)  #열로 병합(=열이 늘어남)
#concat2 = np.concatenate([x2,y2], axis = 0)  #행으로 병합(=행이 늘어남)
print(concat2)

[[1 2 4 5]
 [3 4 6 7]]


In [23]:
arr = np.arange(10)
print(arr)

arr.reshape(2,5)          #2행 5열로 모양 바꿔줌 > 이렇게 맞춰서 병합해야할수도!  ##

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
##병합2 - hstack/ vstack

#hstack : horizontal 수평 
#vstack : vertical 수직

h = np.hstack([x2,y2])
print(h)                  #옆으로/ 수평 - 열로 붙음 

[[1 2 4 5]
 [3 4 6 7]]


In [25]:
v = np.vstack([x2,y2])
print(v)                  #밑으로/ 수직 - 행으로 붙음 

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [30]:
##분할1 - hsplit/ vsplit 

x2 = np.array([[1,2], [3,4], [5,6]])  #dim없다고 나와서 array로 만들어줌 

h2 = np.hsplit(x2,2)   #수평방향의 행을 자르는 것 #따라서 열로 잘림 
print(h2)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [31]:
v2 = np.vsplit(x2,3)
print(v2)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


# 다양한 배열

In [32]:
#0행렬 -.zeros

zero = np.zeros([3,4])     #[3,4,2]하면 3차원 행렬 
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
#1행렬 - .ones

one = np.ones([3,4])
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
#대각행렬: 대각선1/ 나머지 0  - .eye

eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# numpy 제공함수

## 범용함수

In [36]:
#절댓값 - .abs

arr1 = np.array([-1,-2,-3,-4])
abs_arr = np.abs(arr1)

print(abs_arr)

[1 2 3 4]


In [37]:
#제곱근 - .sqrt

arr2 = np.array([1,4,9,16])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 2. 3. 4.]


## 집계함수

In [39]:
#평균 - .mean (실수형)

a = np.array([1,2,3,4,5])
a_mean = np.mean(a)
print(a_mean)

3.0


In [40]:
#중앙값 - .median (실수형)

b = np.array([1,3,5,7,9])
b_median = np.median(b)
print(b_median)

5.0


In [46]:
#최솟값 - .argmin (최솟값의 인덱스 반환!)

min = np.argmin(d)
print(min)

0


In [47]:
#최댓값 - .argmax (인덱스)
max = np.argmax(d)
print(max)

4


In [41]:
#표준편차 - .std (실수형)

c = np.array([1,2,3,4,5])
c_std = np.std(c)
print(c_std)

1.4142135623730951


In [42]:
#분산 - .var (실수형)

d = np.array([1,2,3,4,5])
d_var = np.var(d)
print(d_var)

2.0


In [43]:
#합계 - sum  (값으로 반환)
d_sum = np.sum(d)
print(d_sum)

15


In [44]:
#누적합계 - cumsum (배열형태로 반환!)

d_cumsum = np.cumsum(d)
print(d_cumsum)

[ 1  3  6 10 15]


In [48]:
#배열 안 True 하나라도 있는지 - .any

a = np.array([0,0,0,1])

a_true = np.any(a)
print(a_true)

True


In [50]:
#모든게 1이어야만 True - .all

a_all = np.all(a)
print(a_all)

False


In [51]:
#NaN (not a number) - .nan / nansum:nan을 0으로 대체하여 sum

a= np.array([1,2, np.nan, 4])
a_nsum = np.nansum(a)
sum_ = np.sum(a)            #그냥 sum은 nan 출력됨 

print(a_nsum)
print(sum_)     

7.0
nan


In [57]:
#조건에 맞는'값' 반환 - .where
d = np.array([1,2,3,4,5])

condition1 = np.where(d<3)                                                       #튜플!     
condition2 = np.where(d<3, d, 0)  #조건에 맞는 애들 빼고 나머지는 0으로 만들기   #배열! (!= 리스트) 
print(condition1)
print(condition2)

(array([0, 1]),)
[1 2 0 0 0]


# Boolean Indexing
* 조건에 따른 요소들을 판별해서 '새로운' 배열 만듦 
* 즉 원본데이터는 불변!

In [60]:
a = np.array([1,2,3,4,5,6,7,8,9,10])  #원본 데이터

#데이터분석할때 원본데이터는 건들이지 않는다!! 
#따라서 복사본을 항상 만들어서 분석하기!!! 

In [63]:
even_a = a[a % 2 == 0]  #boolean indexing #짝수만 
print(even_a)
print(a)                #원본 데이터는 변하지 않음! 

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


# Broadcast 브로드캐스트
* 크기가 다른 배열간의 연산 가능하게 해줌 
* 예시) 1차원, 2차원 

* 두 배열의 차원수가 다를경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을때까지 1을 추가한다. 
* 두 배열의 차원수가 같을 경우에도 크기가 1인 차원이 있다면, 다른 배열의 크기와 일치하도록 복제된다. 
* 두 배열의 차원수가 같은 경우에도 모든 차원의 크기가 같거나 1이라면, 모양이 같은 두 배열의 요소간 연산을 한다. 

In [64]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a+b
print(c)    #차원이 동일하기에 그냥 사칙연산 이용하면 됨 

[5 7 9]


In [65]:
d = np.array([[1], [2], [3]])   #차원 다른데        ##행렬은 2차원부터
e = np.array([4,5,6])                                #1차원은 벡터! 

f = d+e
print(f)                        #출력됨 -> numpy의 브로드캐스트 기능! 

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#벡터 1x3으로 바꾸면 
[[1,1,1]] 

In [ ]:
#즉, i) 먼저 같은 차원으로 - e가 벡터이므로 [[]]로 1x3 2차원으로 만듦
#    ii) 같은 차원이더라도, 다른 배열의 크기와 일치하도록 복제 - 양쪽에서 크기 1 차원있으므로 3까지 복제됨 
[[1 1 1      +   [[4 5 6      =  [[5 6 7  
  2 2 2            4 5 6           6 7 8
  3 3 3 ]]         4 5 6 ]]        7 8 9 ]]